CREATE DATABASE CMS;

USE CMS;

CREATE TABLE user (
   id INT AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(50) NOT NULL UNIQUE,
   password VARCHAR(100) NOT NULL,
   name VARCHAR(100) NOT NULL,
   role ENUM('EMPLOYEE', 'ADMIN') NOT NULL,
   mobile VARCHAR(100) NOT NULL,
   image VARCHAR(255)
);

CREATE TABLE complaint (
   id INT AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(100) NOT NULL,
   description TEXT NOT NULL,
   status ENUM('PENDING', 'RESOLVED') DEFAULT 'PENDING',
   remarks TEXT,
   user_id INT NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);